import { html, figma } from "@figma/code-connect/html"

/**
 * -- This file was auto-generated by `figma connect create` --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  "https://www.figma.com/design/eDLFcyA8cJgfULbN7qMIYA/-Test--Figma-library---badge?node-id=1-81&t=Qy5LM8AcLIFFsPzs-1",
  {
    props: {
      variant: figma.enum("Variant", {
        Info: "info",
        Warning: "warning",
        Error: "negative",
        Success: "positive",
        Neutral: "neutral",
        Violet: "violet",
        Pink: "Pink",
      }),
      type: figma.enum("Type", {
        Subtle: "subtle",
        Accent: "accent",
      }),
      showIcon: figma.boolean("Show icon"),
    },
    example: ({variant, type, showIcon}) => html`
    <custom-badge variant="${variant}" type="${type}"}>Badge</custom-badge>
    `,
  },
)
